// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2OWL1s5svFjnnkRx3eadA5zHZh3QG4bg',
    appId: '1:642528939263:web:fa86ccb250091640e790ca',
    messagingSenderId: '642528939263',
    projectId: 'do-an-lap-trinh-di',
    authDomain: 'do-an-lap-trinh-di.firebaseapp.com',
    storageBucket: 'do-an-lap-trinh-di.firebasestorage.app',
    measurementId: 'G-S6JG1Z7DNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8X_OBvsFiJTmnS9QWQZnVQs9aucPcOnc',
    appId: '1:642528939263:android:f3b9cc109a155e8de790ca',
    messagingSenderId: '642528939263',
    projectId: 'do-an-lap-trinh-di',
    storageBucket: 'do-an-lap-trinh-di.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgGhEViNTJMf0JebvjlAgXH89lB-1rCmk',
    appId: '1:642528939263:ios:de4849718f869cc2e790ca',
    messagingSenderId: '642528939263',
    projectId: 'do-an-lap-trinh-di',
    storageBucket: 'do-an-lap-trinh-di.firebasestorage.app',
    iosBundleId: 'com.example.doAnLapTrinhTrenThietBiDiDongMychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgGhEViNTJMf0JebvjlAgXH89lB-1rCmk',
    appId: '1:642528939263:ios:de4849718f869cc2e790ca',
    messagingSenderId: '642528939263',
    projectId: 'do-an-lap-trinh-di',
    storageBucket: 'do-an-lap-trinh-di.firebasestorage.app',
    iosBundleId: 'com.example.doAnLapTrinhTrenThietBiDiDongMychat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2OWL1s5svFjnnkRx3eadA5zHZh3QG4bg',
    appId: '1:642528939263:web:a6d309019dca6d13e790ca',
    messagingSenderId: '642528939263',
    projectId: 'do-an-lap-trinh-di',
    authDomain: 'do-an-lap-trinh-di.firebaseapp.com',
    storageBucket: 'do-an-lap-trinh-di.firebasestorage.app',
    measurementId: 'G-0Q32LPN6YN',
  );

}